/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package src.main.java;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class zoo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5624710670230341665L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"zoo\",\"namespace\":\"src.main.java\",\"fields\":[{\"name\":\"Version\",\"type\":\"int\"},{\"name\":\"Animals\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Animal\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Weight\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<zoo> ENCODER =
      new BinaryMessageEncoder<zoo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<zoo> DECODER =
      new BinaryMessageDecoder<zoo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<zoo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<zoo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<zoo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<zoo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this zoo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a zoo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a zoo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static zoo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int Version;
  private java.util.List<src.main.java.Animal> Animals;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public zoo() {}

  /**
   * All-args constructor.
   * @param Version The new value for Version
   * @param Animals The new value for Animals
   */
  public zoo(java.lang.Integer Version, java.util.List<src.main.java.Animal> Animals) {
    this.Version = Version;
    this.Animals = Animals;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Version;
    case 1: return Animals;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Version = (java.lang.Integer)value$; break;
    case 1: Animals = (java.util.List<src.main.java.Animal>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Version' field.
   * @return The value of the 'Version' field.
   */
  public int getVersion() {
    return Version;
  }


  /**
   * Sets the value of the 'Version' field.
   * @param value the value to set.
   */
  public void setVersion(int value) {
    this.Version = value;
  }

  /**
   * Gets the value of the 'Animals' field.
   * @return The value of the 'Animals' field.
   */
  public java.util.List<src.main.java.Animal> getAnimals() {
    return Animals;
  }


  /**
   * Sets the value of the 'Animals' field.
   * @param value the value to set.
   */
  public void setAnimals(java.util.List<src.main.java.Animal> value) {
    this.Animals = value;
  }

  /**
   * Creates a new zoo RecordBuilder.
   * @return A new zoo RecordBuilder
   */
  public static src.main.java.zoo.Builder newBuilder() {
    return new src.main.java.zoo.Builder();
  }

  /**
   * Creates a new zoo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new zoo RecordBuilder
   */
  public static src.main.java.zoo.Builder newBuilder(src.main.java.zoo.Builder other) {
    if (other == null) {
      return new src.main.java.zoo.Builder();
    } else {
      return new src.main.java.zoo.Builder(other);
    }
  }

  /**
   * Creates a new zoo RecordBuilder by copying an existing zoo instance.
   * @param other The existing instance to copy.
   * @return A new zoo RecordBuilder
   */
  public static src.main.java.zoo.Builder newBuilder(src.main.java.zoo other) {
    if (other == null) {
      return new src.main.java.zoo.Builder();
    } else {
      return new src.main.java.zoo.Builder(other);
    }
  }

  /**
   * RecordBuilder for zoo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<zoo>
    implements org.apache.avro.data.RecordBuilder<zoo> {

    private int Version;
    private java.util.List<src.main.java.Animal> Animals;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(src.main.java.zoo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Version)) {
        this.Version = data().deepCopy(fields()[0].schema(), other.Version);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Animals)) {
        this.Animals = data().deepCopy(fields()[1].schema(), other.Animals);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing zoo instance
     * @param other The existing instance to copy.
     */
    private Builder(src.main.java.zoo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Version)) {
        this.Version = data().deepCopy(fields()[0].schema(), other.Version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Animals)) {
        this.Animals = data().deepCopy(fields()[1].schema(), other.Animals);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Version' field.
      * @return The value.
      */
    public int getVersion() {
      return Version;
    }


    /**
      * Sets the value of the 'Version' field.
      * @param value The value of 'Version'.
      * @return This builder.
      */
    public src.main.java.zoo.Builder setVersion(int value) {
      validate(fields()[0], value);
      this.Version = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Version' field has been set.
      * @return True if the 'Version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Version' field.
      * @return This builder.
      */
    public src.main.java.zoo.Builder clearVersion() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Animals' field.
      * @return The value.
      */
    public java.util.List<src.main.java.Animal> getAnimals() {
      return Animals;
    }


    /**
      * Sets the value of the 'Animals' field.
      * @param value The value of 'Animals'.
      * @return This builder.
      */
    public src.main.java.zoo.Builder setAnimals(java.util.List<src.main.java.Animal> value) {
      validate(fields()[1], value);
      this.Animals = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Animals' field has been set.
      * @return True if the 'Animals' field has been set, false otherwise.
      */
    public boolean hasAnimals() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Animals' field.
      * @return This builder.
      */
    public src.main.java.zoo.Builder clearAnimals() {
      Animals = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public zoo build() {
      try {
        zoo record = new zoo();
        record.Version = fieldSetFlags()[0] ? this.Version : (java.lang.Integer) defaultValue(fields()[0]);
        record.Animals = fieldSetFlags()[1] ? this.Animals : (java.util.List<src.main.java.Animal>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<zoo>
    WRITER$ = (org.apache.avro.io.DatumWriter<zoo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<zoo>
    READER$ = (org.apache.avro.io.DatumReader<zoo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.Version);

    long size0 = this.Animals.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (src.main.java.Animal e0: this.Animals) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Version = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<src.main.java.Animal> a0 = this.Animals;
      if (a0 == null) {
        a0 = new SpecificData.Array<src.main.java.Animal>((int)size0, SCHEMA$.getField("Animals").schema());
        this.Animals = a0;
      } else a0.clear();
      SpecificData.Array<src.main.java.Animal> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<src.main.java.Animal>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          src.main.java.Animal e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new src.main.java.Animal();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Version = in.readInt();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<src.main.java.Animal> a0 = this.Animals;
          if (a0 == null) {
            a0 = new SpecificData.Array<src.main.java.Animal>((int)size0, SCHEMA$.getField("Animals").schema());
            this.Animals = a0;
          } else a0.clear();
          SpecificData.Array<src.main.java.Animal> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<src.main.java.Animal>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              src.main.java.Animal e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new src.main.java.Animal();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










